import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

import { SessionProvider } from "next-auth/react";

import { getServerAuthSession } from "~/server/auth";

import { Provider } from "react";
import ClientSessionProvider from "./_components/ClientSessionProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function  RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <ClientSessionProvider session={session}>
          <TRPCReactProvider cookies={cookies().toString()}>
              {children}
          </TRPCReactProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
